package com.xzy.beans;

public class Address {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address_id
     *
     * @mbggenerated
     */
    private Integer addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address_user_name
     *
     * @mbggenerated
     */
    private String addressUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address_user_tel
     *
     * @mbggenerated
     */
    private String addressUserTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address_a
     *
     * @mbggenerated
     */
    private String addressA;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address_pcode
     *
     * @mbggenerated
     */
    private String addressPcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.address_defalut
     *
     * @mbggenerated
     */
    private Boolean addressDefalut;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address_id
     *
     * @return the value of address.address_id
     *
     * @mbggenerated
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address_id
     *
     * @param addressId the value for address.address_id
     *
     * @mbggenerated
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address_user_name
     *
     * @return the value of address.address_user_name
     *
     * @mbggenerated
     */
    public String getAddressUserName() {
        return addressUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address_user_name
     *
     * @param addressUserName the value for address.address_user_name
     *
     * @mbggenerated
     */
    public void setAddressUserName(String addressUserName) {
        this.addressUserName = addressUserName == null ? null : addressUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address_user_tel
     *
     * @return the value of address.address_user_tel
     *
     * @mbggenerated
     */
    public String getAddressUserTel() {
        return addressUserTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address_user_tel
     *
     * @param addressUserTel the value for address.address_user_tel
     *
     * @mbggenerated
     */
    public void setAddressUserTel(String addressUserTel) {
        this.addressUserTel = addressUserTel == null ? null : addressUserTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address_a
     *
     * @return the value of address.address_a
     *
     * @mbggenerated
     */
    public String getAddressA() {
        return addressA;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address_a
     *
     * @param addressA the value for address.address_a
     *
     * @mbggenerated
     */
    public void setAddressA(String addressA) {
        this.addressA = addressA == null ? null : addressA.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address_pcode
     *
     * @return the value of address.address_pcode
     *
     * @mbggenerated
     */
    public String getAddressPcode() {
        return addressPcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address_pcode
     *
     * @param addressPcode the value for address.address_pcode
     *
     * @mbggenerated
     */
    public void setAddressPcode(String addressPcode) {
        this.addressPcode = addressPcode == null ? null : addressPcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.address_defalut
     *
     * @return the value of address.address_defalut
     *
     * @mbggenerated
     */
    public Boolean getAddressDefalut() {
        return addressDefalut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.address_defalut
     *
     * @param addressDefalut the value for address.address_defalut
     *
     * @mbggenerated
     */
    public void setAddressDefalut(Boolean addressDefalut) {
        this.addressDefalut = addressDefalut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.user_id
     *
     * @return the value of address.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.user_id
     *
     * @param userId the value for address.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}