package com.xzy.beans;

import java.util.Date;

public class Browse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column browse.browse_id
     *
     * @mbggenerated
     */
    private Product product;

    private boolean collect;

    private Integer browseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column browse.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column browse.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column browse.browse_time
     *
     * @mbggenerated
     */
    private Date browseTime;

    public Integer getBrowseId() {
        return browseId;
    }

    public void setBrowseId(Integer browseId) {
        this.browseId = browseId;
    }

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }


    public boolean isCollect() {
        return collect;
    }

    public void setCollect(boolean collect) {
        this.collect = collect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column browse.browse_id
     *
     * @return the value of browse.browse_id
     *
     * @mbggenerated
     */


    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column browse.product_id
     *
     * @param productId the value for browse.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column browse.user_id
     *
     * @return the value of browse.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column browse.user_id
     *
     * @param userId the value for browse.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column browse.browse_time
     *
     * @return the value of browse.browse_time
     *
     * @mbggenerated
     */
    public Date getBrowseTime() {
        return browseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column browse.browse_time
     *
     * @param browseTime the value for browse.browse_time
     *
     * @mbggenerated
     */
    public void setBrowseTime(Date browseTime) {
        this.browseTime = browseTime;
    }

    @Override
    public String toString() {
        return "Browse{" +
                "product=" + product +
                ", collect=" + collect +
                ", browseId=" + browseId +
                ", productId=" + productId +
                ", userId=" + userId +
                ", browseTime=" + browseTime +
                '}';
    }
}