package com.xzy.beans;

public class Carousel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.carousel_id
     *
     * @mbggenerated
     */
    private Integer carouselId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.path
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carousel.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.carousel_id
     *
     * @return the value of carousel.carousel_id
     * @mbggenerated
     */
    public Integer getCarouselId() {
        return carouselId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.carousel_id
     *
     * @param carouselId the value for carousel.carousel_id
     * @mbggenerated
     */
    public void setCarouselId(Integer carouselId) {
        this.carouselId = carouselId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.path
     *
     * @return the value of carousel.path
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.path
     *
     * @param path the value for carousel.path
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carousel.product_id
     *
     * @return the value of carousel.product_id
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carousel.product_id
     *
     * @param productId the value for carousel.product_id
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
}