package com.xzy.beans;

public class CartProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_product.cart_product_id
     *
     * @mbggenerated
     */
    private Integer cartProductId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_product.quantity
     *
     * @mbggenerated
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_product.checked
     *
     * @mbggenerated
     */
    private Integer checked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_product.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_product.cart_id
     *
     * @mbggenerated
     */
    private Integer cartId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cart_product.is_alive
     *
     * @mbggenerated
     */
    private Integer isAlive;

    private String cpProductSize;

    private String cpProductColor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_product.cart_product_id
     *
     * @return the value of cart_product.cart_product_id
     * @mbggenerated
     */
    public Integer getCartProductId() {
        return cartProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_product.cart_product_id
     *
     * @param cartProductId the value for cart_product.cart_product_id
     * @mbggenerated
     */
    public void setCartProductId(Integer cartProductId) {
        this.cartProductId = cartProductId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_product.quantity
     *
     * @return the value of cart_product.quantity
     * @mbggenerated
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_product.quantity
     *
     * @param quantity the value for cart_product.quantity
     * @mbggenerated
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_product.checked
     *
     * @return the value of cart_product.checked
     * @mbggenerated
     */
    public Integer getChecked() {
        return checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_product.checked
     *
     * @param checked the value for cart_product.checked
     * @mbggenerated
     */
    public void setChecked(Integer checked) {
        this.checked = checked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_product.product_id
     *
     * @return the value of cart_product.product_id
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_product.product_id
     *
     * @param productId the value for cart_product.product_id
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_product.cart_id
     *
     * @return the value of cart_product.cart_id
     * @mbggenerated
     */
    public Integer getCartId() {
        return cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_product.cart_id
     *
     * @param cartId the value for cart_product.cart_id
     * @mbggenerated
     */
    public void setCartId(Integer cartId) {
        this.cartId = cartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cart_product.is_alive
     *
     * @return the value of cart_product.is_alive
     * @mbggenerated
     */
    public Integer getIsAlive() {
        return isAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cart_product.is_alive
     *
     * @param isAlive the value for cart_product.is_alive
     * @mbggenerated
     */
    public void setIsAlive(Integer isAlive) {
        this.isAlive = isAlive;
    }

    public String getCpProductSize() {
        return cpProductSize;
    }

    public void setCpProductSize(String cpProductSize) {
        this.cpProductSize = cpProductSize;
    }

    public String getCpProductColor() {
        return cpProductColor;
    }

    public void setCpProductColor(String cpProductColor) {
        this.cpProductColor = cpProductColor;
    }
}