package com.xzy.beans;

public class Collect {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.collect_id
     *
     * @mbggenerated
     */
    private Integer collectId;



    private  Integer  State;

    public Integer getState() {
        return State;
    }

    @Override
    public String toString() {
        return "Collect{" +
                "collectId=" + collectId +
                ", State=" + State +
                ", userId=" + userId +
                ", productId=" + productId +
                ", browse=" + browse +
                '}';
    }

    public void setState(Integer state) {
        State = state;
    }

    private Integer userId;


    private Integer productId;


    private  Browse browse;

    public Browse getBrowse() {
        return browse;
    }

    public void setBrowse(Browse browse) {
        this.browse = browse;
    }

    public Integer getCollectId() {
        return collectId;
    }

    public void setCollectId(Integer collectId) {
        this.collectId = collectId;
    }

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getProductId() {
        return productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }
}