package com.xzy.beans;

public class Collect {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.collect_id
     *
     * @mbggenerated
     */
    private Integer collectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.collect_id
     *
     * @return the value of collect.collect_id
     *
     * @mbggenerated
     */
    private Integer state;
    public  Integer getState() {return state;}
    public  void setState(Integer state) {this.state=state;}

    public Integer getCollectId() {
        return collectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.collect_id
     *
     * @param collectId the value for collect.collect_id
     *
     * @mbggenerated
     */
    public void setCollectId(Integer collectId) {
        this.collectId = collectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.user_id
     *
     * @return the value of collect.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.user_id
     *
     * @param userId the value for collect.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect.product_id
     *
     * @return the value of collect.product_id
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect.product_id
     *
     * @param productId the value for collect.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
}