package com.xzy.beans;

public class Orderitem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.orderitem_id
     *
     * @mbggenerated
     */
    private Integer orderitemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.oi_product_num
     *
     * @mbggenerated
     */
    private Integer oiProductNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.oi_total_price
     *
     * @mbggenerated
     */
    private Float oiTotalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderitem.orders_id
     *
     * @mbggenerated
     */
    private Integer ordersId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.orderitem_id
     *
     * @return the value of orderitem.orderitem_id
     *
     * @mbggenerated
     */
    public Integer getOrderitemId() {
        return orderitemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.orderitem_id
     *
     * @param orderitemId the value for orderitem.orderitem_id
     *
     * @mbggenerated
     */
    public void setOrderitemId(Integer orderitemId) {
        this.orderitemId = orderitemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.oi_product_num
     *
     * @return the value of orderitem.oi_product_num
     *
     * @mbggenerated
     */
    public Integer getOiProductNum() {
        return oiProductNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.oi_product_num
     *
     * @param oiProductNum the value for orderitem.oi_product_num
     *
     * @mbggenerated
     */
    public void setOiProductNum(Integer oiProductNum) {
        this.oiProductNum = oiProductNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.oi_total_price
     *
     * @return the value of orderitem.oi_total_price
     *
     * @mbggenerated
     */
    public Float getOiTotalPrice() {
        return oiTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.oi_total_price
     *
     * @param oiTotalPrice the value for orderitem.oi_total_price
     *
     * @mbggenerated
     */
    public void setOiTotalPrice(Float oiTotalPrice) {
        this.oiTotalPrice = oiTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.product_id
     *
     * @return the value of orderitem.product_id
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.product_id
     *
     * @param productId the value for orderitem.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderitem.orders_id
     *
     * @return the value of orderitem.orders_id
     *
     * @mbggenerated
     */
    public Integer getOrdersId() {
        return ordersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderitem.orders_id
     *
     * @param ordersId the value for orderitem.orders_id
     *
     * @mbggenerated
     */
    public void setOrdersId(Integer ordersId) {
        this.ordersId = ordersId;
    }
}