package com.xzy.beans;

import java.util.Date;

public class Orders {


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orders_id
     *
     * @mbggenerated
     */
    private Integer ordersId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orders_total_price
     *
     * @mbggenerated
     */
    private Float ordersTotalPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orders_pay_status
     *
     * @mbggenerated
     */
    private Integer ordersPayStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orders_send_status
     *
     * @mbggenerated
     */
    private Integer ordersSendStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orders_get_status
     *
     * @mbggenerated
     */
    private Integer ordersGetStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orders_create_time
     *
     * @mbggenerated
     */
    private Date ordersCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orders_send_time
     *
     * @mbggenerated
     */
    private Date ordersSendTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orders_get_time
     *
     * @mbggenerated
     */
    private Date ordersGetTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.address_id
     *
     * @mbggenerated
     */
    private Integer addressId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orders_id
     *
     * @return the value of orders.orders_id
     *
     * @mbggenerated
     */
    public Integer getOrdersId() {
        return ordersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orders_id
     *
     * @param ordersId the value for orders.orders_id
     *
     * @mbggenerated
     */
    public void setOrdersId(Integer ordersId) {
        this.ordersId = ordersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orders_total_price
     *
     * @return the value of orders.orders_total_price
     *
     * @mbggenerated
     */
    public Float getOrdersTotalPrice() {
        return ordersTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orders_total_price
     *
     * @param ordersTotalPrice the value for orders.orders_total_price
     *
     * @mbggenerated
     */
    public void setOrdersTotalPrice(Float ordersTotalPrice) {
        this.ordersTotalPrice = ordersTotalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orders_pay_status
     *
     * @return the value of orders.orders_pay_status
     *
     * @mbggenerated
     */
    public Integer getOrdersPayStatus() {
        return ordersPayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orders_pay_status
     *
     * @param ordersPayStatus the value for orders.orders_pay_status
     *
     * @mbggenerated
     */
    public void setOrdersPayStatus(Integer ordersPayStatus) {
        this.ordersPayStatus = ordersPayStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orders_send_status
     *
     * @return the value of orders.orders_send_status
     *
     * @mbggenerated
     */
    public Integer getOrdersSendStatus() {
        return ordersSendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orders_send_status
     *
     * @param ordersSendStatus the value for orders.orders_send_status
     *
     * @mbggenerated
     */
    public void setOrdersSendStatus(Integer ordersSendStatus) {
        this.ordersSendStatus = ordersSendStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orders_get_status
     *
     * @return the value of orders.orders_get_status
     *
     * @mbggenerated
     */
    public Integer getOrdersGetStatus() {
        return ordersGetStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orders_get_status
     *
     * @param ordersGetStatus the value for orders.orders_get_status
     *
     * @mbggenerated
     */
    public void setOrdersGetStatus(Integer ordersGetStatus) {
        this.ordersGetStatus = ordersGetStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orders_create_time
     *
     * @return the value of orders.orders_create_time
     *
     * @mbggenerated
     */
    public Date getOrdersCreateTime() {
        return ordersCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orders_create_time
     *
     * @param ordersCreateTime the value for orders.orders_create_time
     *
     * @mbggenerated
     */
    public void setOrdersCreateTime(Date ordersCreateTime) {
        this.ordersCreateTime = ordersCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orders_send_time
     *
     * @return the value of orders.orders_send_time
     *
     * @mbggenerated
     */
    public Date getOrdersSendTime() {
        return ordersSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orders_send_time
     *
     * @param ordersSendTime the value for orders.orders_send_time
     *
     * @mbggenerated
     */
    public void setOrdersSendTime(Date ordersSendTime) {
        this.ordersSendTime = ordersSendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orders_get_time
     *
     * @return the value of orders.orders_get_time
     *
     * @mbggenerated
     */
    public Date getOrdersGetTime() {
        return ordersGetTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orders_get_time
     *
     * @param ordersGetTime the value for orders.orders_get_time
     *
     * @mbggenerated
     */
    public void setOrdersGetTime(Date ordersGetTime) {
        this.ordersGetTime = ordersGetTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.user_id
     *
     * @return the value of orders.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.user_id
     *
     * @param userId the value for orders.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.address_id
     *
     * @return the value of orders.address_id
     *
     * @mbggenerated
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.address_id
     *
     * @param addressId the value for orders.address_id
     *
     * @mbggenerated
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }


}