package com.xzy.beans;

public class ProductDetails {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_details.product_details_id
     *
     * @mbggenerated
     */
    private Integer productDetailsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_details.product_dsize
     *
     * @mbggenerated
     */
    private String productDsize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_details.product_dcolor
     *
     * @mbggenerated
     */
    private String productDcolor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_details.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_details.product_details_id
     *
     * @return the value of product_details.product_details_id
     *
     * @mbggenerated
     */
    public Integer getProductDetailsId() {
        return productDetailsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_details.product_details_id
     *
     * @param productDetailsId the value for product_details.product_details_id
     *
     * @mbggenerated
     */
    public void setProductDetailsId(Integer productDetailsId) {
        this.productDetailsId = productDetailsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_details.product_dsize
     *
     * @return the value of product_details.product_dsize
     *
     * @mbggenerated
     */
    public String getProductDsize() {
        return productDsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_details.product_dsize
     *
     * @param productDsize the value for product_details.product_dsize
     *
     * @mbggenerated
     */
    public void setProductDsize(String productDsize) {
        this.productDsize = productDsize == null ? null : productDsize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_details.product_dcolor
     *
     * @return the value of product_details.product_dcolor
     *
     * @mbggenerated
     */
    public String getProductDcolor() {
        return productDcolor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_details.product_dcolor
     *
     * @param productDcolor the value for product_details.product_dcolor
     *
     * @mbggenerated
     */
    public void setProductDcolor(String productDcolor) {
        this.productDcolor = productDcolor == null ? null : productDcolor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_details.product_id
     *
     * @return the value of product_details.product_id
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_details.product_id
     *
     * @param productId the value for product_details.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
}