package com.xzy.beans;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;
import java.util.List;

public class Seckill {

    public Long getNowTime() {
        return nowTime;
    }

    public void setNowTime(long nowTime) {
        this.nowTime = nowTime;
    }

    private Long nowTime;

    private List<Product> like;

    public List<Product> getLike() {
        return like;
    }

    public void setLike(List<Product> like) {
        this.like = like;
    }

    private int countDiscuss;

    public int getCountDiscuss() {
        return countDiscuss;
    }

    public void setCountDiscuss(int countDiscuss) {
        this.countDiscuss = countDiscuss;
    }

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    private Product product;

    private Information information;

    public Information getInformation() {
        return information;
    }

    public void setInformation(Information information) {
        this.information = information;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.seckill_id
     *
     * @mbggenerated
     */
    private Integer seckillId;
    private String seckillTitle;
    private Float seckillPrice;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.seckill_start_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date seckillStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.seckill_end_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    private Date seckillEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.seckill_create_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")


    private Date seckillCreateTime;
    private Integer seckillStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    public Integer getSeckillId() {
        return seckillId;
    }

    public void setSeckillId(Integer seckillId) {
        this.seckillId = seckillId;
    }

    public String getSeckillTitle() {
        return seckillTitle;
    }

    public void setSeckillTitle(String seckillTitle) {
        this.seckillTitle = seckillTitle;
    }

    public Float getSeckillPrice() {
        return seckillPrice;
    }

    public void setSeckillPrice(Float seckillPrice) {
        this.seckillPrice = seckillPrice;
    }

    public Date getSeckillStartTime() {
        return seckillStartTime;
    }

    public void setSeckillStartTime(Date seckillStartTime) {
        this.seckillStartTime = seckillStartTime;
    }

    public Date getSeckillEndTime() {
        return seckillEndTime;
    }

    public void setSeckillEndTime(Date seckillEndTime) {
        this.seckillEndTime = seckillEndTime;
    }

    public Date getSeckillCreateTime() {
        return seckillCreateTime;
    }

    public void setSeckillCreateTime(Date seckillCreateTime) {
        this.seckillCreateTime = seckillCreateTime;
    }

    public Integer getSeckillStock() {
        return seckillStock;
    }

    public void setSeckillStock(Integer seckillStock) {
        this.seckillStock = seckillStock;
    }

    public Integer getProductId() {
        return productId;
    }

    public void setProductId(Integer productId) {
        this.productId = productId;
    }
}