package com.xzy.beans;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class Seckill {

    private int countDiscuss;

    public int getCountDiscuss() {
        return countDiscuss;
    }

    public void setCountDiscuss(int countDiscuss) {
        this.countDiscuss = countDiscuss;
    }

    public Product getProduct() {
        return product;
    }

    public void setProduct(Product product) {
        this.product = product;
    }

    private Product product;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.seckill_id
     *
     * @mbggenerated
     */
    private Integer seckillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.seckill_title
     *
     * @mbggenerated
     */
    private String seckillTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.seckill_price
     *
     * @mbggenerated
     */
    private Float seckillPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.seckill_start_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    @JsonFormat(timezone = "GMT+8",pattern = "yyyy-MM-dd HH:mm:ss")
    private Date seckillStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.seckill_end_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    @JsonFormat(timezone = "GMT+8",pattern = "yyyy-MM-dd HH:mm:ss")
    private Date seckillEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.seckill_create_time
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    @JsonFormat(timezone = "GMT+8",pattern = "yyyy-MM-dd HH:mm:ss")
    private Date seckillCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.seckill_stock
     *
     * @mbggenerated
     */
    private Integer seckillStock;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.product_id
     *
     * @mbggenerated
     */
    private Integer productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.seckill_id
     *
     * @return the value of seckill.seckill_id
     *
     * @mbggenerated
     */
    public Integer getSeckillId() {
        return seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.seckill_id
     *
     * @param seckillId the value for seckill.seckill_id
     *
     * @mbggenerated
     */
    public void setSeckillId(Integer seckillId) {
        this.seckillId = seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.seckill_title
     *
     * @return the value of seckill.seckill_title
     *
     * @mbggenerated
     */
    public String getSeckillTitle() {
        return seckillTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.seckill_title
     *
     * @param seckillTitle the value for seckill.seckill_title
     *
     * @mbggenerated
     */
    public void setSeckillTitle(String seckillTitle) {
        this.seckillTitle = seckillTitle == null ? null : seckillTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.seckill_price
     *
     * @return the value of seckill.seckill_price
     *
     * @mbggenerated
     */
    public Float getSeckillPrice() {
        return seckillPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.seckill_price
     *
     * @param seckillPrice the value for seckill.seckill_price
     *
     * @mbggenerated
     */
    public void setSeckillPrice(Float seckillPrice) {
        this.seckillPrice = seckillPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.seckill_start_time
     *
     * @return the value of seckill.seckill_start_time
     *
     * @mbggenerated
     */
    public Date getSeckillStartTime() {
        return seckillStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.seckill_start_time
     *
     * @param seckillStartTime the value for seckill.seckill_start_time
     *
     * @mbggenerated
     */
    public void setSeckillStartTime(Date seckillStartTime) {
        this.seckillStartTime = seckillStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.seckill_end_time
     *
     * @return the value of seckill.seckill_end_time
     *
     * @mbggenerated
     */
    public Date getSeckillEndTime() {
        return seckillEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.seckill_end_time
     *
     * @param seckillEndTime the value for seckill.seckill_end_time
     *
     * @mbggenerated
     */
    public void setSeckillEndTime(Date seckillEndTime) {
        this.seckillEndTime = seckillEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.seckill_create_time
     *
     * @return the value of seckill.seckill_create_time
     *
     * @mbggenerated
     */
    public Date getSeckillCreateTime() {
        return seckillCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.seckill_create_time
     *
     * @param seckillCreateTime the value for seckill.seckill_create_time
     *
     * @mbggenerated
     */
    public void setSeckillCreateTime(Date seckillCreateTime) {
        this.seckillCreateTime = seckillCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.seckill_stock
     *
     * @return the value of seckill.seckill_stock
     *
     * @mbggenerated
     */
    public Integer getSeckillStock() {
        return seckillStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.seckill_stock
     *
     * @param seckillStock the value for seckill.seckill_stock
     *
     * @mbggenerated
     */
    public void setSeckillStock(Integer seckillStock) {
        this.seckillStock = seckillStock;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.product_id
     *
     * @return the value of seckill.product_id
     *
     * @mbggenerated
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.product_id
     *
     * @param productId the value for seckill.product_id
     *
     * @mbggenerated
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
}