package com.xzy.beans;

import java.util.Date;

public class User {

    private Integer userId;

    private String userName;

    private String userPassword;

    private String userEmail;

    private String userTel;

    private String userBirth;

    private String userCreat;

    private String userReal;

    private String userSex;

    private byte[] userPic;

    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_id
     *
     * @param userId the value for user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * @return the value of user.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     *
     * @param userName the value for user.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_password
     *
     * @return the value of user.user_password
     *
     * @mbggenerated
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_password
     *
     * @param userPassword the value for user.user_password
     *
     * @mbggenerated
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_email
     *
     * @return the value of user.user_email
     *
     * @mbggenerated
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_email
     *
     * @param userEmail the value for user.user_email
     *
     * @mbggenerated
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_tel
     *
     * @return the value of user.user_tel
     *
     * @mbggenerated
     */
    public String getUserTel() {
        return userTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_tel
     *
     * @param userTel the value for user.user_tel
     *
     * @mbggenerated
     */
    public void setUserTel(String userTel) {
        this.userTel = userTel == null ? null : userTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_birth
     *
     * @return the value of user.user_birth
     *
     * @mbggenerated
     */
    public String getUserBirth() {
        return userBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_birth
     *
     * @param userBirth the value for user.user_birth
     *
     * @mbggenerated
     */
    public void setUserBirth(String userBirth) {
        this.userBirth = userBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_creat
     *
     * @return the value of user.user_creat
     *
     * @mbggenerated
     */
    public String getUserCreat() {
        return userCreat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_creat
     *
     * @param userCreat the value for user.user_creat
     *
     * @mbggenerated
     */
    public void setUserCreat(String userCreat) {
        this.userCreat = userCreat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_real
     *
     * @return the value of user.user_real
     *
     * @mbggenerated
     */
    public String getUserReal() {
        return userReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_real
     *
     * @param userReal the value for user.user_real
     *
     * @mbggenerated
     */
    public void setUserReal(String userReal) {
        this.userReal = userReal == null ? null : userReal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_sex
     *
     * @return the value of user.user_sex
     *
     * @mbggenerated
     */
    public String getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_sex
     *
     * @param userSex the value for user.user_sex
     *
     * @mbggenerated
     */
    public void setUserSex(String userSex) {
        this.userSex = userSex == null ? null : userSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_pic
     *
     * @return the value of user.user_pic
     *
     * @mbggenerated
     */
    public byte[] getUserPic() {
        return userPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_pic
     *
     * @param userPic the value for user.user_pic
     *
     * @mbggenerated
     */
    public void setUserPic(byte[] userPic) {
        this.userPic = userPic;
    }
}