package com.xzy.mapper;

import com.xzy.beans.Browse;

public interface BrowseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer browseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse
     *
     * @mbggenerated
     */
    int insert(Browse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse
     *
     * @mbggenerated
     */
    int insertSelective(Browse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse
     *
     * @mbggenerated
     */
    Browse selectByPrimaryKey(Integer browseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Browse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Browse record);
}