package com.xzy.mapper;

import com.xzy.beans.Browse;

import java.util.List;

public interface BrowseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse
     *
     * @mbggenerated
     */
    //    删除一条浏览记录
    void deleteHistory(Integer userId, Integer productId);
    //    根据用户id查询商品浏览记录表
    List<Browse> selectHistoryByUserId(Integer userId);
    //    根据用户id和商品id查询浏览记录
     Browse selectHistoryByUserIdAndProductId(Browse userHistory);

    //    更新浏览历史表
    void updateByupdateHistory(Browse record);

    /*插入商品到浏览历史表*/
    void insertHistory(Browse userHistory);



    int deleteByPrimaryKey(Integer browseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse
     *
     * @mbggenerated
     */
    int insert(Browse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse
     *
     * @mbggenerated
     */
    Browse selectByPrimaryKey(Integer browseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browse
     *
     * @mbggenerated
     */


    int updateByPrimaryKey(Browse record);
}