package com.xzy.mapper;

import com.xzy.beans.Cart;
import com.xzy.beans.CartItem;

import java.util.List;
import java.util.Map;

import com.xzy.beans.Cart;

public interface CartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer cartId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_product
     *
     * @mbggenerated
     */
    int insert(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_product
     *
     * @mbggenerated
     */
    int insertSelective(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_product
     *
     * @mbggenerated
     */
    Cart selectByPrimaryKey(Integer cartId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Cart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Cart record);

    public List<CartItem> selectAllCartItemByOneUser(Integer userId);

    public void deleteCartItem(Map map);

    public void insertCartItem(Cart cart);

    public void updateQuantity(Cart cart);

    public List<Cart> selectCart(Integer userId);
}

