package com.xzy.mapper;

import com.xzy.beans.CartProduct;

public interface CartProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer cartProductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_product
     *
     * @mbggenerated
     */
    int insert(CartProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_product
     *
     * @mbggenerated
     */
    int insertSelective(CartProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_product
     *
     * @mbggenerated
     */
    CartProduct selectByPrimaryKey(Integer cartProductId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CartProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cart_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CartProduct record);
}