package com.xzy.mapper;

import com.xzy.beans.ProductDiscuss;

import java.util.Map;

public interface ProductDiscussMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_discuss
     *
     * @mbggenerated
     */
    //查询评论条数（根据订单id查询）
    Integer countDiscuss(Integer ProductId);

    int deleteByPrimaryKey(Integer productDiscussId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_discuss
     *
     * @mbggenerated
     */
    int insert(ProductDiscuss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_discuss
     *
     * @mbggenerated
     */
    void insertSelective(ProductDiscuss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_discuss
     *
     * @mbggenerated
     */
    ProductDiscuss selectByPrimaryKey(Integer productDiscussId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_discuss
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProductDiscuss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_discuss
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductDiscuss record);
}