package com.xzy.mapper;

import com.xzy.beans.ProductDetails;

public interface ProductDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_details
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer productDetailsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_details
     *
     * @mbggenerated
     */
    int insert(ProductDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_details
     *
     * @mbggenerated
     */
    int insertSelective(ProductDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_details
     *
     * @mbggenerated
     */
    ProductDetails selectByPrimaryKey(Integer productDetailsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_details
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProductDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_details
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductDetails record);
}