package com.xzy.mapper;

import com.xzy.beans.ProductDiscuss;

import java.util.Map;

public interface ProductDiscussMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_discuss
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer productDiscussId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_discuss
     *
     * @mbggenerated
     */
    int insert(ProductDiscuss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_discuss
     *
     * @mbggenerated
     */
    void insertSelective(ProductDiscuss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_discuss
     *
     * @mbggenerated
     */
    ProductDiscuss selectByPrimaryKey(Integer productDiscussId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_discuss
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProductDiscuss record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_discuss
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductDiscuss record);

    /**
     * 查询商品对应评价总条数
     * @param productId
     * @return
     */
    int countDiscuss(Integer productId);
}