spring:
  rabbitmq:
    host: 192.168.176.134
    port: 5672
    username: admin
    password: CRD199821
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    #   数据源基本配置
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.102.123.133:3306/infintyshop?useSSL=false&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource

    #数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500


  # REDIS (RedisProperties)
  # Redis数据库索引（默认为0）
  # Redis服务器地址
  # Redis服务器连接端口
  # Redis服务器连接密码（默认为空）
  # 连接超时时间（毫秒）
  # 连接池最大连接数（使用负值表示没有限制）
  # 连接池最大阻塞等待时间（使用负值表示没有限制）
  # 连接池中的最大空闲连接
  # 连接池中的最小空闲连接
  redis:
    database: 0
    host: 192.168.176.134
    port: 6379
    timeout: 0
    password:
    jedis:
      pool:
        max-active: 3000
        max-wait: -1
        max-idle: 8
        min-idle: 0

#扫描mybatis主配置文件，*Mapper.xml文件
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

preread:
  #文件上传目录（注意Linux和Windows上的目录结构不同）
  uploadPath: E:/image/

